export enum RiskReasonCode {
  NONE = 'NONE',
  QUANTITY_LIMIT_EXCEEDED = 'QUANTITY_LIMIT_EXCEEDED',
  NOTIONAL_LIMIT_EXCEEDED = 'NOTIONAL_LIMIT_EXCEEDED',
  MULTIPLE_LIMITS_EXCEEDED = 'MULTIPLE_LIMITS_EXCEEDED',
}
